# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20161116_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Teacher'),
        ),
    ]
